# ใช้ Node.js version 18 (Image ขนาดเล็ก)
FROM node:18-alpine

# กำหนดโฟลเดอร์ทำงานใน Container
WORKDIR /app

# ก๊อปปี้ไฟล์ package.json ไปก่อนเพื่อลงโปรแกรม
COPY package*.json ./

# ติดตั้ง Library ต่างๆ
RUN npm install

# ก๊อปปี้โค้ดทั้งหมดเข้าไป
COPY . .

# เปิด Port 3000
EXPOSE 3000

# คำสั่งรัน Server
CMD ["npm", "start"]